### ISSUE TITLE
Converting ONNX to TensorRT(.trt)

### ISSUE THREAD

**Issue by ejhung** [ibaiGorordo/ONNX-MobileStereoNet#2]
Firstly, thank you for providing excellent work.

I was about to work on converting the mobilestereonet onnx model to TensorRT model to improve inference speed.
Even though I confirmed my own model was well converted to onnx using your work, but issues come up as I tried to convert the onnx to a TensorRT model.

Have you tried the conversion? If so, it will be great if you could share your process since I'm struggling with various issues.
I've tried TRT6 in Ubuntu18.04, CUDA10.1 environment.

Thanks again!

**Comment by ibaiGorordo** [comment]
Hi,

I have not tried to use TensorRT, so unfortunately won't be of much help.

**Comment by ejhung** [comment]
Thank you for the response though!
