### ISSUE TITLE
Unable to locate the model file

### ISSUE THREAD

**Issue by anustupc** [ibaiGorordo/ONNX-MobileStereoNet#4]
Hi, It seems as if the model file is not available in the PINTO_model_zoo folder. Will it be possible for you to upload the onnx file?
Thanks.

**Comment by ibaiGorordo** [comment]
https://drive.google.com/file/d/1Dkyrg5Fu554gqxfclkHC6zJBCYrdzOO0/view?usp=sharing

**Comment by anustupc** [comment]
Thanks
