### ISSUE TITLE
I also want to convert mobilestereonet to onnx but I have tried many methods without success, always getting an error, I want a code reference for converting mobile stereonet to onnx, thank you

### ISSUE THREAD

**Issue by dididichufale** [ibaiGorordo/ONNX-MobileStereoNet#5]

**Comment by dididichufale** [comment]
i want to converting mobilestereonet3d to onnx    i think ConvTranspose3d dont support onnx  always error，so i want to get a code reference for  mobilestereonet3d to onnx

**Comment by hebangwen** [comment]
Hi, you can find a reference code in [my fork](https://github.com/BangwenHe/mobilestereonet/blob/dev/convert.py). Just replace `MSNet2D` with `MSNet3D` and it should be fine. Please note one drawback of my converting code is that the result model size can be up to 200MB.

**Comment by dididichufale** [comment]
Thank you, I have successfully converted onnx. I found a bug in mobilenet3d. The size of the image you input must be a multiple of 16 to convert, because it is down-sampled by 16 times, and the image size must be changed to meet the multiple of 16.
